
/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.ayam.learn.logback;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Main {
    private static final Logger logger = LoggerFactory.getLogger(Main.class);

    public static void main(String[] args) {
        logger.info("Application started using multiple appenders.");
        logger.warn("This is a warning log that goes to both Console and File appenders.");
        logger.error("Something went wrong! Check your log files.");

        System.out.println("Check the 'logs/' folder to see the results!");
    }
}
