
/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.ayam.learn.logback;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Main {
    private static final Logger logger = LoggerFactory.getLogger(Main.class);

    public static void main(String[] args) {
        logger.trace("Trace log - very detailed info.");
        logger.debug("Debug information is visible if log level is set in logback.xml");
        logger.info("Logging started dynamically!");
        logger.warn("Be careful with those logs!");
        logger.error("Error logging example!");

        System.out.println("Standard System.out still works too.");
    }
}
