
/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.ayam.learn.logback;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Main {
    private static final Logger logger = LoggerFactory.getLogger(Main.class);

    public static void main(String[] args) {
        logger.info("Application started. Rolling policy is active.");

        // Let's log a bunch of messages to trigger a 'roll'
        // Our limit in logback.xml is set very small (10KB) just for this lab!
        for (int i = 1; i <= 500; i++) {
            logger.info("This is message number {} - Filling up the log file...", i);
        }

        logger.info("Finished logging 500 messages. Now, check 'logs/archived/' folder!");
    }
}
